# Generated by Django 5.0.6 on 2024-05-13 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='kategor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cakes', to='torts.kategor'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CakeOrder',
            fields=[
                ('cake_id1', models.AutoField(primary_key=True, serialize=False)),
                ('cake_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('order_description', models.TextField()),
                ('cake_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cakes', to='torts.cake')),
            ],
        ),
    ]
